name: Bug report
description: Report errors and problems
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        :earth_americas: **English Only**
        
        To maintain a welcoming and inclusive environment for everyone, please fill out this issue in English.
        
        This helps ensure that all contributors can easily understand and engage in the conversation. :handshake::star2:

        Thank you for your understanding! :handshake::star2:
        
        ---
  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](../../CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Contributing Guidelines.
          required: true
  - type: input
    id: plugin
    attributes:
      label: Plugin Version
      description: Which plugin versions are affected?
      placeholder: "1.0.0, 1.2.1, 2.0.3"
    validations:
      required: true
  - type: input
    id: moodle
    attributes:
      label: Moodle Version
      description: Which Moodle are affected?
      placeholder: "3.9, 4.1, 4.2, 4.3"
    validations:
      required: true
  - type: input
    id: database
    attributes:
      label: Affected Database Type
      description: Does this only occur on specific database type?
      placeholder: "MariaDB, Postgres, MySQL"
    validations:
      required: true
  - type: input
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Are there any similar existing issues?
      placeholder: "#123"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly and concisely describe the bug.
      placeholder: Tell us what happened.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      value: |
        1. 
        2. 
        3. 
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What should have happened?
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Please include code snippets, stack traces, or compiler errors.
      placeholder: Paste code snippets ans stack traces here
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: Add screenshots, or videos to help explain your problem.
      placeholder: Upload screenshots, and videos here
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other useful information about the problem here.
      placeholder: Is there any additional helpful information you can share?
    validations:
      required: false
