name: Feature request
description: Suggest an idea
title: "[Feature]: "
labels: ["feature request", "enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        :earth_americas: **English Only**
        
        To maintain a welcoming and inclusive environment for everyone, please fill out this issue in English.
        
        This helps ensure that all contributors can easily understand and engage in the conversation.
        
        Thank you for your understanding! :handshake::star2:

        ---
  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](../../CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Contributing Guidelines.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly and concisely describe what you would like to change, add, or implement.
      placeholder: Tell us your idea.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem?
      placeholder: What problem will this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this be solved?
      placeholder: How do you think this should be implemented?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Are there other possible approaches?
      placeholder: Can you think of any other options?
    validations:
      required: true
